Update tests.yml
Signed-off-by: ArchBlood <35392110+ArchBlood@users.noreply.github.com>

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -23,13 +23,15 @@ jobs:
       - name: Build Docker image
         run: |
           docker build --platform=linux/amd64 -t humhub-docker -f Dockerfile .
-          echo "Docker images:"
-          docker images
-          echo "Docker inspect humhub-docker:"
-          docker inspect humhub-docker || true
         continue-on-error: true
 
+      - name: Check if Docker image exists
+        id: check-image-exists
+        run: |
+          docker image inspect humhub-docker >/dev/null 2>&1 || exit 1
+
       - name: Check PHP Version in Dockerfile
+        if: steps.check-image-exists.outcome == 'success'
         id: check-php-version
         run: |
           PHP_VERSION=$(docker inspect --format='{{index .Config.Labels "org.opencontainers.image.source"}}' humhub-docker | grep -oP '(?<=FROM php:)([0-9]+\.[0-9]+)')
@@ -40,8 +42,8 @@ jobs:
 
       - name: Cleanup
         run: |
-          docker image rm humhub-test || true
+          docker image rm humhub-docker || true
 
       - name: Set failed status if PHP version check failed
-        if: ${{ failure() || steps.check-php-version.outcome == 'failure' }}
-        run: exit 1  # Set the workflow status to failed if PHP version check failed
+        if: steps.check-image-exists.outcome == 'success' && steps.check-php-version.outcome == 'failure'
+        run: exit 1  # Set the workflow status to failed if the PHP version check failed
