Update test.yml
Signed-off-by: ArchBlood <35392110+ArchBlood@users.noreply.github.com>

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -46,34 +46,22 @@ jobs:
       - name: Check Docker build status
         run: docker inspect humhub-test
 
-      - name: Verify PHP installation
+      - name: Verify Docker image
         run: |
           docker run --rm humhub-test php -v || echo "::error::PHP verification failed"
-
-      - name: Verify Apache installation
-        run: |
           docker run --rm humhub-test apache2 -v || echo "::error::Apache verification failed"
 
+      - name: Start container and check cron status
+        run: docker run --rm -d --name humhub-container humhub-test
+        
+      - name: Check cron service status
+        run: docker exec humhub-container service cron status || echo "::error::Cron service verification failed"
+
       - name: Copy crontab
-        run: cp src/crontab /tmp/crontab
+        run: docker cp src/crontab humhub-container:/etc/cron.d/humhub-cron
 
-      - name: Check crontab
-        run: |
-          docker run --rm -v /tmp/crontab:/etc/cron.d/humhub-cron humhub-test bash -c 'chmod 0644 /etc/cron.d/humhub-cron && cat /etc/cron.d/humhub-cron' || echo "::error::Crontab verification failed"
-
-      - name: Verify cron service
-        run: |
-          docker run --rm humhub-test bash -c 'service cron status || echo "::error::Cron service verification failed"'
-
-      - name: Verify Apache and cron running together
-        run: |
-          docker run --rm -d --name humhub-container humhub-test
-          sleep 10 # Give it a moment to initialize
-          docker logs humhub-container
-          docker exec humhub-container pgrep cron || echo "::error::Cron is not running"
-          docker exec humhub-container pgrep apache2 || echo "::error::Apache is not running"
-          docker stop humhub-container
+      - name: Verify crontab
+        run: docker exec humhub-container bash -c 'chmod 0644 /etc/cron.d/humhub-cron && cat /etc/cron.d/humhub-cron' || echo "::error::Crontab verification failed"
 
       - name: Cleanup
-        run: |
-          docker image rm humhub-test || true
+        run: docker stop humhub-container || true && docker rm humhub-container || true
